channels:
  - plotly
  - http://conda.anaconda.org/gabrielelanaro
  - http://ssb.stsci.edu/astroconda
  - astropy
  - stsci
  - bioconda
  - tboch
  - conda-forge
  - defaults
dependencies:
  - astroml
  - astropy
  - astroquery
  - pandas
  - plotly
  - plotly_express
  pip:
    - ipyaladin
  
