channels:
  - plotly
  - http://conda.anaconda.org/gabrielelanaro
  - http://ssb.stsci.edu/astroconda
  - astropy
  - stsci
  - bioconda
  - tboch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - astroml=0.4.post1
  - astropy=3.2.1
  - astroquery=0.3.9
  - pandas=0.25.1
  - plotly=4.0.0
  - plotly_express=0.4.0
  pip:
    - ipyaladin
  
